alphabet = list(map(chr, range(ord('A'), ord('Z') + 1)))
VAR = "VAR"
NOT = "NOT"
CONJ = "CONJ"
DISJ = "DISJ"
IMPL = "IMPL"
BIIMPL = "BIIMPL"
LPAREN = "LPAREN"
RPAREN = "RPAREN"
operations = [NOT,CONJ,DISJ,IMPL,BIIMPL]
Invalid_Input = 0